#!/usr/bin/env node
/**
 * Lists skills whose metadata.reviewed is older than N days. Used by the weekly staleness workflow
 * to open or update a tracking issue, and locally to see what needs a re-read.
 *
 *   node tools/staleness-report.ts [--days 90] [--format text|markdown|json] [--skills-dir skills]
 */
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { parseArgs } from 'node:util'
import { listSkillFolders, loadSkill } from '../src/core/skill-loader.ts'
import type { SkillMetadata } from '../src/core/types.ts'

export interface StaleSkill {
  name: string
  owner: string
  reviewed: string
  ageDays: number
  version: string
}

export async function findStaleSkills(skillsDir: string, maxAgeDays: number, today = new Date()): Promise<StaleSkill[]> {
  const stale: StaleSkill[] = []
  for (const folder of await listSkillFolders(skillsDir)) {
    const skill = await loadSkill(skillsDir, folder)
    const metadata = (skill.frontmatter['metadata'] ?? {}) as Partial<SkillMetadata>
    const rawReviewed: unknown = metadata.reviewed
    const reviewed = rawReviewed instanceof Date ? rawReviewed.toISOString().slice(0, 10) : String(rawReviewed ?? '')
    const reviewedDate = new Date(`${reviewed}T00:00:00Z`)
    if (Number.isNaN(reviewedDate.getTime())) {
      stale.push({ name: folder, owner: metadata.owner ?? '?', reviewed: 'invalid', ageDays: Number.POSITIVE_INFINITY, version: String(metadata.version ?? '?') })
      continue
    }
    const ageDays = Math.floor((today.getTime() - reviewedDate.getTime()) / 86_400_000)
    if (ageDays > maxAgeDays) stale.push({ name: folder, owner: metadata.owner ?? '?', reviewed, ageDays, version: String(metadata.version ?? '?') })
  }
  return stale.sort((a, b) => b.ageDays - a.ageDays)
}

export function formatMarkdown(stale: StaleSkill[], maxAgeDays: number, repo: string): string {
  if (!stale.length) return `All skills were reviewed within the last ${maxAgeDays} days.`
  const owners = [...new Set(stale.map((skill) => skill.owner).filter((owner) => owner.startsWith('@')))]
  const lines = [
    `The following skills have not been reviewed in more than ${maxAgeDays} days. Owners: re-read the skill, fix anything that drifted, bump \`metadata.version\` if content changed, and set \`metadata.reviewed\` to today.`,
    '',
    '| Skill | Owner | Last reviewed | Age (days) | Version |',
    '|---|---|---|---|---|',
    ...stale.map((skill) => `| [${skill.name}](https://github.com/${repo}/blob/main/skills/${skill.name}/SKILL.md) | ${skill.owner} | ${skill.reviewed} | ${Number.isFinite(skill.ageDays) ? skill.ageDays : 'unknown'} | ${skill.version} |`),
    '',
    owners.length ? `cc ${owners.join(' ')}` : '',
    '',
    '_Generated by the staleness workflow (`npm run staleness`). This issue is updated weekly and closed automatically when nothing is stale._',
  ]
  return lines.join('\n').trim()
}

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: {
      days: { type: 'string', default: '90' },
      format: { type: 'string', default: 'text' },
      'skills-dir': { type: 'string', default: 'skills' },
      repo: { type: 'string', default: 'maiconsouza89/mass-agents-skills' },
    },
  })
  const maxAgeDays = Number(values.days)
  const stale = await findStaleSkills(resolve(values['skills-dir']!), maxAgeDays)
  if (values.format === 'json') console.log(JSON.stringify({ maxAgeDays, stale }, null, 2))
  else if (values.format === 'markdown') console.log(formatMarkdown(stale, maxAgeDays, values.repo!))
  else if (!stale.length) console.log(`all skills reviewed within ${maxAgeDays} days`)
  else for (const skill of stale) console.log(`${skill.name.padEnd(32)} ${skill.owner.padEnd(18)} ${skill.reviewed}  ${skill.ageDays} days`)
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error(error)
    process.exit(1)
  })
}
